inkscape -z -e "pngs/0_cm.png" -w 64 -h 64 "0cm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/0_cs.png" -w 64 -h 64 "0cs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/0_jvn.png" -w 64 -h 64 "0jvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/0_phv.png" -w 64 -h 64 "0phv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/0.png" -w 64 -h 64 "0.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/1_cm.png" -w 64 -h 64 "1cm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/1_cs.png" -w 64 -h 64 "1cs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/1_jvn.png" -w 64 -h 64 "1jvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/1_phv.png" -w 64 -h 64 "1phv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/1.png" -w 64 -h 64 "1.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/2_cm.png" -w 64 -h 64 "2cm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/2_cs.png" -w 64 -h 64 "2cs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/2_jvn.png" -w 64 -h 64 "2jvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/2_phv.png" -w 64 -h 64 "2phv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/2.png" -w 64 -h 64 "2.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/3_cm.png" -w 64 -h 64 "3cm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/3_cs.png" -w 64 -h 64 "3cs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/3_jvn.png" -w 64 -h 64 "3jvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/3_phv.png" -w 64 -h 64 "3phv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/3.png" -w 64 -h 64 "3.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/4_cm.png" -w 64 -h 64 "4cm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/4_cs.png" -w 64 -h 64 "4cs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/4_jvn.png" -w 64 -h 64 "4jvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/4_phv.png" -w 64 -h 64 "4phv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/4.png" -w 64 -h 64 "4.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/5_cm.png" -w 64 -h 64 "5cm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/5_cs.png" -w 64 -h 64 "5cs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/5_jvn.png" -w 64 -h 64 "5jvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/5_phv.png" -w 64 -h 64 "5phv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/5.png" -w 64 -h 64 "5.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/6_cm.png" -w 64 -h 64 "6cm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/6_cs.png" -w 64 -h 64 "6cs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/6_jvn.png" -w 64 -h 64 "6jvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/6_phv.png" -w 64 -h 64 "6phv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/6.png" -w 64 -h 64 "6.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/7_cm.png" -w 64 -h 64 "7cm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/7_cs.png" -w 64 -h 64 "7cs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/7_jvn.png" -w 64 -h 64 "7jvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/7_phv.png" -w 64 -h 64 "7phv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/7.png" -w 64 -h 64 "7.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/8_cm.png" -w 64 -h 64 "8cm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/8_cs.png" -w 64 -h 64 "8cs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/8_jvn.png" -w 64 -h 64 "8jvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/8_phv.png" -w 64 -h 64 "8phv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/8.png" -w 64 -h 64 "8.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/9_cm.png" -w 64 -h 64 "9cm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/9_cs.png" -w 64 -h 64 "9cs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/9_jvn.png" -w 64 -h 64 "9jvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/9_phv.png" -w 64 -h 64 "9phv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/9.png" -w 64 -h 64 "9.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/a_cm.png" -w 64 -h 64 "acm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/A_cm.png" -w 64 -h 64 "Acm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/a_cs.png" -w 64 -h 64 "acs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/A_cs.png" -w 64 -h 64 "Acs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/a_jvn.png" -w 64 -h 64 "ajvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/A_jvn.png" -w 64 -h 64 "Ajvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/alpha_cm.png" -w 64 -h 64 "alphacm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/alpha_cs.png" -w 64 -h 64 "alphacs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/alpha_jvn.png" -w 64 -h 64 "alphajvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/alpha_phv.png" -w 64 -h 64 "alphaphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/alpha.png" -w 64 -h 64 "alpha.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/a_phv.png" -w 64 -h 64 "aphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/A_phv.png" -w 64 -h 64 "Aphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/a.png" -w 64 -h 64 "a.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/A.png" -w 64 -h 64 "A.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/b_cm.png" -w 64 -h 64 "bcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/B_cm.png" -w 64 -h 64 "Bcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/b_cs.png" -w 64 -h 64 "bcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/B_cs.png" -w 64 -h 64 "Bcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/beta_cm.png" -w 64 -h 64 "betacm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/beta_cs.png" -w 64 -h 64 "betacs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/beta_jvn.png" -w 64 -h 64 "betajvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/beta_phv.png" -w 64 -h 64 "betaphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/beta.png" -w 64 -h 64 "beta.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/b_jvn.png" -w 64 -h 64 "bjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/B_jvn.png" -w 64 -h 64 "Bjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/b_phv.png" -w 64 -h 64 "bphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/B_phv.png" -w 64 -h 64 "Bphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/b.png" -w 64 -h 64 "b.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/B.png" -w 64 -h 64 "B.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/c_cm.png" -w 64 -h 64 "ccm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/C_cm.png" -w 64 -h 64 "Ccm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/c_cs.png" -w 64 -h 64 "ccs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/C_cs.png" -w 64 -h 64 "Ccs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/chi_cm.png" -w 64 -h 64 "chicm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/chi_cs.png" -w 64 -h 64 "chics.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/chi_jvn.png" -w 64 -h 64 "chijvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/chi_phv.png" -w 64 -h 64 "chiphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/chi.png" -w 64 -h 64 "chi.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/c_jvn.png" -w 64 -h 64 "cjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/C_jvn.png" -w 64 -h 64 "Cjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/<_cm.png" -w 64 -h 64 "<cm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/=_cm.png" -w 64 -h 64 "=cm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/>_cm.png" -w 64 -h 64 ">cm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/-_cm.png" -w 64 -h 64 "-cm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/,_cm.png" -w 64 -h 64 ",cm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/;_cm.png" -w 64 -h 64 ";cm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/:_cm.png" -w 64 -h 64 ":cm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/!_cm.png" -w 64 -h 64 "!cm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/?_cm.png" -w 64 -h 64 "?cm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/(_cm.png" -w 64 -h 64 "(cm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/)_cm.png" -w 64 -h 64 ")cm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/[_cm.png" -w 64 -h 64 "[cm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/@_cm.png" -w 64 -h 64 "@cm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/*_cm.png" -w 64 -h 64 "*cm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/+_cm.png" -w 64 -h 64 "+cm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/cm.png" -w 64 -h 64 "cm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/c_phv.png" -w 64 -h 64 "cphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/C_phv.png" -w 64 -h 64 "Cphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/<_cs.png" -w 64 -h 64 "<cs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/=_cs.png" -w 64 -h 64 "=cs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/>_cs.png" -w 64 -h 64 ">cs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/-_cs.png" -w 64 -h 64 "-cs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/,_cs.png" -w 64 -h 64 ",cs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/;_cs.png" -w 64 -h 64 ";cs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/:_cs.png" -w 64 -h 64 ":cs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/!_cs.png" -w 64 -h 64 "!cs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/?_cs.png" -w 64 -h 64 "?cs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/(_cs.png" -w 64 -h 64 "(cs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/)_cs.png" -w 64 -h 64 ")cs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/[_cs.png" -w 64 -h 64 "[cs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/@_cs.png" -w 64 -h 64 "@cs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/*_cs.png" -w 64 -h 64 "*cs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/+_cs.png" -w 64 -h 64 "+cs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/c.png" -w 64 -h 64 "c.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/C.png" -w 64 -h 64 "C.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/d_cm.png" -w 64 -h 64 "dcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/D_cm.png" -w 64 -h 64 "Dcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/d_cs.png" -w 64 -h 64 "dcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/D_cs.png" -w 64 -h 64 "Dcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/delta_cm.png" -w 64 -h 64 "deltacm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Delta_cm.png" -w 64 -h 64 "Deltacm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/delta_cs.png" -w 64 -h 64 "deltacs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Delta_cs.png" -w 64 -h 64 "Deltacs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/delta_jvn.png" -w 64 -h 64 "deltajvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Delta_jvn.png" -w 64 -h 64 "Deltajvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/delta_phv.png" -w 64 -h 64 "deltaphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Delta_phv.png" -w 64 -h 64 "Deltaphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/delta.png" -w 64 -h 64 "delta.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Delta.png" -w 64 -h 64 "Delta.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/d_jvn.png" -w 64 -h 64 "djvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/D_jvn.png" -w 64 -h 64 "Djvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/d_phv.png" -w 64 -h 64 "dphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/D_phv.png" -w 64 -h 64 "Dphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/d.png" -w 64 -h 64 "d.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/D.png" -w 64 -h 64 "D.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/e_cm.png" -w 64 -h 64 "ecm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/E_cm.png" -w 64 -h 64 "Ecm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/e_cs.png" -w 64 -h 64 "ecs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/E_cs.png" -w 64 -h 64 "Ecs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/e_jvn.png" -w 64 -h 64 "ejvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/E_jvn.png" -w 64 -h 64 "Ejvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/e_phv.png" -w 64 -h 64 "ephv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/E_phv.png" -w 64 -h 64 "Ephv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/epsilon_cm.png" -w 64 -h 64 "epsiloncm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/epsilon_cs.png" -w 64 -h 64 "epsiloncs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/epsilon_jvn.png" -w 64 -h 64 "epsilonjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/epsilon_phv.png" -w 64 -h 64 "epsilonphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/epsilon.png" -w 64 -h 64 "epsilon.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/e.png" -w 64 -h 64 "e.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/E.png" -w 64 -h 64 "E.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/eta_cm.png" -w 64 -h 64 "etacm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/eta_cs.png" -w 64 -h 64 "etacs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/eta_jvn.png" -w 64 -h 64 "etajvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/eta_phv.png" -w 64 -h 64 "etaphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/eta.png" -w 64 -h 64 "eta.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/f_cm.png" -w 64 -h 64 "fcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/F_cm.png" -w 64 -h 64 "Fcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/f_cs.png" -w 64 -h 64 "fcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/F_cs.png" -w 64 -h 64 "Fcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/f_jvn.png" -w 64 -h 64 "fjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/F_jvn.png" -w 64 -h 64 "Fjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/f_phv.png" -w 64 -h 64 "fphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/F_phv.png" -w 64 -h 64 "Fphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/f.png" -w 64 -h 64 "f.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/F.png" -w 64 -h 64 "F.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/gamma_cm.png" -w 64 -h 64 "gammacm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Gamma_cm.png" -w 64 -h 64 "Gammacm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/gamma_cs.png" -w 64 -h 64 "gammacs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Gamma_cs.png" -w 64 -h 64 "Gammacs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/gamma_jvn.png" -w 64 -h 64 "gammajvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Gamma_jvn.png" -w 64 -h 64 "Gammajvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/gamma_phv.png" -w 64 -h 64 "gammaphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Gamma_phv.png" -w 64 -h 64 "Gammaphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/gamma.png" -w 64 -h 64 "gamma.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Gamma.png" -w 64 -h 64 "Gamma.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/g_cm.png" -w 64 -h 64 "gcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/G_cm.png" -w 64 -h 64 "Gcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/g_cs.png" -w 64 -h 64 "gcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/G_cs.png" -w 64 -h 64 "Gcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/g_jvn.png" -w 64 -h 64 "gjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/G_jvn.png" -w 64 -h 64 "Gjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/g_phv.png" -w 64 -h 64 "gphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/G_phv.png" -w 64 -h 64 "Gphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/g.png" -w 64 -h 64 "g.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/G.png" -w 64 -h 64 "G.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/h_cm.png" -w 64 -h 64 "hcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/H_cm.png" -w 64 -h 64 "Hcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/h_cs.png" -w 64 -h 64 "hcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/H_cs.png" -w 64 -h 64 "Hcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/h_jvn.png" -w 64 -h 64 "hjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/H_jvn.png" -w 64 -h 64 "Hjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/h_phv.png" -w 64 -h 64 "hphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/H_phv.png" -w 64 -h 64 "Hphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/h.png" -w 64 -h 64 "h.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/H.png" -w 64 -h 64 "H.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/i_cm.png" -w 64 -h 64 "icm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/I_cm.png" -w 64 -h 64 "Icm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/i_cs.png" -w 64 -h 64 "ics.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/I_cs.png" -w 64 -h 64 "Ics.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/i_jvn.png" -w 64 -h 64 "ijvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/I_jvn.png" -w 64 -h 64 "Ijvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/int_cm.png" -w 64 -h 64 "intcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/int_cs.png" -w 64 -h 64 "intcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/int_jvn.png" -w 64 -h 64 "intjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/int_phv.png" -w 64 -h 64 "intphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/int.png" -w 64 -h 64 "int.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/iota_cm.png" -w 64 -h 64 "iotacm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/iota_cs.png" -w 64 -h 64 "iotacs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/iota_jvn.png" -w 64 -h 64 "iotajvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/iota_phv.png" -w 64 -h 64 "iotaphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/iota.png" -w 64 -h 64 "iota.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/i_phv.png" -w 64 -h 64 "iphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/I_phv.png" -w 64 -h 64 "Iphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/i.png" -w 64 -h 64 "i.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/I.png" -w 64 -h 64 "I.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/j_cm.png" -w 64 -h 64 "jcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/J_cm.png" -w 64 -h 64 "Jcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/j_cs.png" -w 64 -h 64 "jcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/J_cs.png" -w 64 -h 64 "Jcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/j_jvn.png" -w 64 -h 64 "jjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/J_jvn.png" -w 64 -h 64 "Jjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/j_phv.png" -w 64 -h 64 "jphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/J_phv.png" -w 64 -h 64 "Jphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/j.png" -w 64 -h 64 "j.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/J.png" -w 64 -h 64 "J.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/<_jvn.png" -w 64 -h 64 "<jvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/=_jvn.png" -w 64 -h 64 "=jvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/>_jvn.png" -w 64 -h 64 ">jvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/-_jvn.png" -w 64 -h 64 "-jvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/,_jvn.png" -w 64 -h 64 ",jvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/;_jvn.png" -w 64 -h 64 ";jvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/:_jvn.png" -w 64 -h 64 ":jvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/!_jvn.png" -w 64 -h 64 "!jvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/?_jvn.png" -w 64 -h 64 "?jvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/(_jvn.png" -w 64 -h 64 "(jvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/)_jvn.png" -w 64 -h 64 ")jvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/[_jvn.png" -w 64 -h 64 "[jvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/@_jvn.png" -w 64 -h 64 "@jvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/*_jvn.png" -w 64 -h 64 "*jvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/+_jvn.png" -w 64 -h 64 "+jvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/jvn.png" -w 64 -h 64 "jvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/kappa_cm.png" -w 64 -h 64 "kappacm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/kappa_cs.png" -w 64 -h 64 "kappacs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/kappa_jvn.png" -w 64 -h 64 "kappajvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/kappa_phv.png" -w 64 -h 64 "kappaphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/kappa.png" -w 64 -h 64 "kappa.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/k_cm.png" -w 64 -h 64 "kcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/K_cm.png" -w 64 -h 64 "Kcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/k_cs.png" -w 64 -h 64 "kcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/K_cs.png" -w 64 -h 64 "Kcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/k_jvn.png" -w 64 -h 64 "kjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/K_jvn.png" -w 64 -h 64 "Kjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/k_phv.png" -w 64 -h 64 "kphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/K_phv.png" -w 64 -h 64 "Kphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/k.png" -w 64 -h 64 "k.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/K.png" -w 64 -h 64 "K.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/lambda_cm.png" -w 64 -h 64 "lambdacm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Lambda_cm.png" -w 64 -h 64 "Lambdacm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/lambda_cs.png" -w 64 -h 64 "lambdacs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Lambda_cs.png" -w 64 -h 64 "Lambdacs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/lambda_jvn.png" -w 64 -h 64 "lambdajvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Lambda_jvn.png" -w 64 -h 64 "Lambdajvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/lambda_phv.png" -w 64 -h 64 "lambdaphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Lambda_phv.png" -w 64 -h 64 "Lambdaphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/lambda.png" -w 64 -h 64 "lambda.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Lambda.png" -w 64 -h 64 "Lambda.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/l_cm.png" -w 64 -h 64 "lcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/L_cm.png" -w 64 -h 64 "Lcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/l_cs.png" -w 64 -h 64 "lcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/L_cs.png" -w 64 -h 64 "Lcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/l_jvn.png" -w 64 -h 64 "ljvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/L_jvn.png" -w 64 -h 64 "Ljvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/l_phv.png" -w 64 -h 64 "lphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/L_phv.png" -w 64 -h 64 "Lphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/l.png" -w 64 -h 64 "l.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/L.png" -w 64 -h 64 "L.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/m_cm.png" -w 64 -h 64 "mcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/M_cm.png" -w 64 -h 64 "Mcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/m_cs.png" -w 64 -h 64 "mcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/M_cs.png" -w 64 -h 64 "Mcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/m_jvn.png" -w 64 -h 64 "mjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/M_jvn.png" -w 64 -h 64 "Mjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/m_phv.png" -w 64 -h 64 "mphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/M_phv.png" -w 64 -h 64 "Mphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/m.png" -w 64 -h 64 "m.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/M.png" -w 64 -h 64 "M.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/mu_cm.png" -w 64 -h 64 "mucm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/mu_cs.png" -w 64 -h 64 "mucs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/mu_jvn.png" -w 64 -h 64 "mujvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/mu_phv.png" -w 64 -h 64 "muphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/mu.png" -w 64 -h 64 "mu.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/n_cm.png" -w 64 -h 64 "ncm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/N_cm.png" -w 64 -h 64 "Ncm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/n_cs.png" -w 64 -h 64 "ncs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/N_cs.png" -w 64 -h 64 "Ncs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/n_jvn.png" -w 64 -h 64 "njvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/N_jvn.png" -w 64 -h 64 "Njvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/n_phv.png" -w 64 -h 64 "nphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/N_phv.png" -w 64 -h 64 "Nphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/n.png" -w 64 -h 64 "n.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/N.png" -w 64 -h 64 "N.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/nu_cm.png" -w 64 -h 64 "nucm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/nu_cs.png" -w 64 -h 64 "nucs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/nu_jvn.png" -w 64 -h 64 "nujvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/nu_phv.png" -w 64 -h 64 "nuphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/nu.png" -w 64 -h 64 "nu.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/o_cm.png" -w 64 -h 64 "ocm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/O_cm.png" -w 64 -h 64 "Ocm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/o_cs.png" -w 64 -h 64 "ocs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/O_cs.png" -w 64 -h 64 "Ocs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/o_jvn.png" -w 64 -h 64 "ojvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/O_jvn.png" -w 64 -h 64 "Ojvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/omega_cm.png" -w 64 -h 64 "omegacm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Omega_cm.png" -w 64 -h 64 "Omegacm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/omega_cs.png" -w 64 -h 64 "omegacs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Omega_cs.png" -w 64 -h 64 "Omegacs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/omega_jvn.png" -w 64 -h 64 "omegajvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Omega_jvn.png" -w 64 -h 64 "Omegajvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/omega_phv.png" -w 64 -h 64 "omegaphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Omega_phv.png" -w 64 -h 64 "Omegaphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/omega.png" -w 64 -h 64 "omega.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Omega.png" -w 64 -h 64 "Omega.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/o_phv.png" -w 64 -h 64 "ophv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/O_phv.png" -w 64 -h 64 "Ophv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/o.png" -w 64 -h 64 "o.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/O.png" -w 64 -h 64 "O.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/p_cm.png" -w 64 -h 64 "pcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/P_cm.png" -w 64 -h 64 "Pcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/p_cs.png" -w 64 -h 64 "pcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/P_cs.png" -w 64 -h 64 "Pcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/phi_cm.png" -w 64 -h 64 "phicm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Phi_cm.png" -w 64 -h 64 "Phicm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/phi_cs.png" -w 64 -h 64 "phics.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Phi_cs.png" -w 64 -h 64 "Phics.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/phi_jvn.png" -w 64 -h 64 "phijvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Phi_jvn.png" -w 64 -h 64 "Phijvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/phi_phv.png" -w 64 -h 64 "phiphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Phi_phv.png" -w 64 -h 64 "Phiphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/phi.png" -w 64 -h 64 "phi.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Phi.png" -w 64 -h 64 "Phi.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/<_phv.png" -w 64 -h 64 "<phv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/=_phv.png" -w 64 -h 64 "=phv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/>_phv.png" -w 64 -h 64 ">phv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/-_phv.png" -w 64 -h 64 "-phv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/,_phv.png" -w 64 -h 64 ",phv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/;_phv.png" -w 64 -h 64 ";phv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/:_phv.png" -w 64 -h 64 ":phv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/!_phv.png" -w 64 -h 64 "!phv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/?_phv.png" -w 64 -h 64 "?phv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/(_phv.png" -w 64 -h 64 "(phv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/)_phv.png" -w 64 -h 64 ")phv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/[_phv.png" -w 64 -h 64 "[phv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/@_phv.png" -w 64 -h 64 "@phv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/*_phv.png" -w 64 -h 64 "*phv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/+_phv.png" -w 64 -h 64 "+phv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/pi_cm.png" -w 64 -h 64 "picm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Pi_cm.png" -w 64 -h 64 "Picm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/pi_cs.png" -w 64 -h 64 "pics.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Pi_cs.png" -w 64 -h 64 "Pics.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/pi_jvn.png" -w 64 -h 64 "pijvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Pi_jvn.png" -w 64 -h 64 "Pijvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/pi_phv.png" -w 64 -h 64 "piphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Pi_phv.png" -w 64 -h 64 "Piphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/pi.png" -w 64 -h 64 "pi.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Pi.png" -w 64 -h 64 "Pi.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/p_jvn.png" -w 64 -h 64 "pjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/P_jvn.png" -w 64 -h 64 "Pjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/p_phv.png" -w 64 -h 64 "pphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/P_phv.png" -w 64 -h 64 "Pphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/prod_cm.png" -w 64 -h 64 "prodcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/prod_cs.png" -w 64 -h 64 "prodcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/prod_jvn.png" -w 64 -h 64 "prodjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/prod_phv.png" -w 64 -h 64 "prodphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/prod.png" -w 64 -h 64 "prod.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/psi_cm.png" -w 64 -h 64 "psicm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Psi_cm.png" -w 64 -h 64 "Psicm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/psi_cs.png" -w 64 -h 64 "psics.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Psi_cs.png" -w 64 -h 64 "Psics.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/psi_jvn.png" -w 64 -h 64 "psijvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Psi_jvn.png" -w 64 -h 64 "Psijvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/psi_phv.png" -w 64 -h 64 "psiphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Psi_phv.png" -w 64 -h 64 "Psiphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/psi.png" -w 64 -h 64 "psi.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Psi.png" -w 64 -h 64 "Psi.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/p.png" -w 64 -h 64 "p.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/P.png" -w 64 -h 64 "P.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/q_cm.png" -w 64 -h 64 "qcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Q_cm.png" -w 64 -h 64 "Qcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/q_cs.png" -w 64 -h 64 "qcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Q_cs.png" -w 64 -h 64 "Qcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/q_jvn.png" -w 64 -h 64 "qjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Q_jvn.png" -w 64 -h 64 "Qjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/q_phv.png" -w 64 -h 64 "qphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Q_phv.png" -w 64 -h 64 "Qphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/q.png" -w 64 -h 64 "q.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Q.png" -w 64 -h 64 "Q.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/r_cm.png" -w 64 -h 64 "rcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/R_cm.png" -w 64 -h 64 "Rcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/r_cs.png" -w 64 -h 64 "rcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/R_cs.png" -w 64 -h 64 "Rcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/rho_cm.png" -w 64 -h 64 "rhocm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/rho_cs.png" -w 64 -h 64 "rhocs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/rho_jvn.png" -w 64 -h 64 "rhojvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/rho_phv.png" -w 64 -h 64 "rhophv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/rho.png" -w 64 -h 64 "rho.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/r_jvn.png" -w 64 -h 64 "rjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/R_jvn.png" -w 64 -h 64 "Rjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/r_phv.png" -w 64 -h 64 "rphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/R_phv.png" -w 64 -h 64 "Rphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/r.png" -w 64 -h 64 "r.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/R.png" -w 64 -h 64 "R.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/s_cm.png" -w 64 -h 64 "scm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/S_cm.png" -w 64 -h 64 "Scm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/s_cs.png" -w 64 -h 64 "scs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/S_cs.png" -w 64 -h 64 "Scs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/sigma_cm.png" -w 64 -h 64 "sigmacm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Sigma_cm.png" -w 64 -h 64 "Sigmacm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/sigma_cs.png" -w 64 -h 64 "sigmacs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Sigma_cs.png" -w 64 -h 64 "Sigmacs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/sigma_jvn.png" -w 64 -h 64 "sigmajvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Sigma_jvn.png" -w 64 -h 64 "Sigmajvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/sigma_phv.png" -w 64 -h 64 "sigmaphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Sigma_phv.png" -w 64 -h 64 "Sigmaphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/sigma.png" -w 64 -h 64 "sigma.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Sigma.png" -w 64 -h 64 "Sigma.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/s_jvn.png" -w 64 -h 64 "sjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/S_jvn.png" -w 64 -h 64 "Sjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/s_phv.png" -w 64 -h 64 "sphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/S_phv.png" -w 64 -h 64 "Sphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/s.png" -w 64 -h 64 "s.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/S.png" -w 64 -h 64 "S.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/sum_cm.png" -w 64 -h 64 "sumcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/sum_cs.png" -w 64 -h 64 "sumcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/sum_jvn.png" -w 64 -h 64 "sumjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/sum_phv.png" -w 64 -h 64 "sumphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/sum.png" -w 64 -h 64 "sum.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/<.png" -w 64 -h 64 "<.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/=.png" -w 64 -h 64 "=.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/>.png" -w 64 -h 64 ">.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/-.png" -w 64 -h 64 "-.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/,.png" -w 64 -h 64 ",.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/;.png" -w 64 -h 64 ";.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/:.png" -w 64 -h 64 ":.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/!.png" -w 64 -h 64 "!.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/?.png" -w 64 -h 64 "?.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/(.png" -w 64 -h 64 "(.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/).png" -w 64 -h 64 ").svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/[.png" -w 64 -h 64 "[.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/@.png" -w 64 -h 64 "@.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/*.png" -w 64 -h 64 "*.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/+.png" -w 64 -h 64 "+.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/tau_cm.png" -w 64 -h 64 "taucm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/tau_cs.png" -w 64 -h 64 "taucs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/tau_jvn.png" -w 64 -h 64 "taujvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/tau_phv.png" -w 64 -h 64 "tauphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/tau.png" -w 64 -h 64 "tau.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/t_cm.png" -w 64 -h 64 "tcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/T_cm.png" -w 64 -h 64 "Tcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/t_cs.png" -w 64 -h 64 "tcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/T_cs.png" -w 64 -h 64 "Tcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/theta_cm.png" -w 64 -h 64 "thetacm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Theta_cm.png" -w 64 -h 64 "Thetacm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/theta_cs.png" -w 64 -h 64 "thetacs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Theta_cs.png" -w 64 -h 64 "Thetacs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/theta_jvn.png" -w 64 -h 64 "thetajvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Theta_jvn.png" -w 64 -h 64 "Thetajvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/theta_phv.png" -w 64 -h 64 "thetaphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Theta_phv.png" -w 64 -h 64 "Thetaphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/theta.png" -w 64 -h 64 "theta.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Theta.png" -w 64 -h 64 "Theta.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/t_jvn.png" -w 64 -h 64 "tjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/T_jvn.png" -w 64 -h 64 "Tjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/t_phv.png" -w 64 -h 64 "tphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/T_phv.png" -w 64 -h 64 "Tphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/t.png" -w 64 -h 64 "t.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/T.png" -w 64 -h 64 "T.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/u_cm.png" -w 64 -h 64 "ucm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/U_cm.png" -w 64 -h 64 "Ucm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/u_cs.png" -w 64 -h 64 "ucs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/U_cs.png" -w 64 -h 64 "Ucs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/u_jvn.png" -w 64 -h 64 "ujvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/U_jvn.png" -w 64 -h 64 "Ujvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/u_phv.png" -w 64 -h 64 "uphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/U_phv.png" -w 64 -h 64 "Uphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/upsilon_cm.png" -w 64 -h 64 "upsiloncm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Upsilon_cm.png" -w 64 -h 64 "Upsiloncm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/upsilon_cs.png" -w 64 -h 64 "upsiloncs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Upsilon_cs.png" -w 64 -h 64 "Upsiloncs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/upsilon_jvn.png" -w 64 -h 64 "upsilonjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Upsilon_jvn.png" -w 64 -h 64 "Upsilonjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/upsilon_phv.png" -w 64 -h 64 "upsilonphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Upsilon_phv.png" -w 64 -h 64 "Upsilonphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/upsilon.png" -w 64 -h 64 "upsilon.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Upsilon.png" -w 64 -h 64 "Upsilon.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/u.png" -w 64 -h 64 "u.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/U.png" -w 64 -h 64 "U.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/v_cm.png" -w 64 -h 64 "vcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/V_cm.png" -w 64 -h 64 "Vcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/v_cs.png" -w 64 -h 64 "vcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/V_cs.png" -w 64 -h 64 "Vcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/v_jvn.png" -w 64 -h 64 "vjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/V_jvn.png" -w 64 -h 64 "Vjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/v_phv.png" -w 64 -h 64 "vphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/V_phv.png" -w 64 -h 64 "Vphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/v.png" -w 64 -h 64 "v.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/V.png" -w 64 -h 64 "V.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/w_cm.png" -w 64 -h 64 "wcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/W_cm.png" -w 64 -h 64 "Wcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/w_cs.png" -w 64 -h 64 "wcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/W_cs.png" -w 64 -h 64 "Wcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/w_jvn.png" -w 64 -h 64 "wjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/W_jvn.png" -w 64 -h 64 "Wjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/w_phv.png" -w 64 -h 64 "wphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/W_phv.png" -w 64 -h 64 "Wphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/w.png" -w 64 -h 64 "w.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/W.png" -w 64 -h 64 "W.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/x_cm.png" -w 64 -h 64 "xcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/X_cm.png" -w 64 -h 64 "Xcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/x_cs.png" -w 64 -h 64 "xcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/X_cs.png" -w 64 -h 64 "Xcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/x_jvn.png" -w 64 -h 64 "xjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/X_jvn.png" -w 64 -h 64 "Xjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/x_phv.png" -w 64 -h 64 "xphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/X_phv.png" -w 64 -h 64 "Xphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/x.png" -w 64 -h 64 "x.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/X.png" -w 64 -h 64 "X.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/y_cm.png" -w 64 -h 64 "ycm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Y_cm.png" -w 64 -h 64 "Ycm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/y_cs.png" -w 64 -h 64 "ycs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Y_cs.png" -w 64 -h 64 "Ycs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/y_jvn.png" -w 64 -h 64 "yjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Y_jvn.png" -w 64 -h 64 "Yjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/y_phv.png" -w 64 -h 64 "yphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Y_phv.png" -w 64 -h 64 "Yphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/y.png" -w 64 -h 64 "y.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Y.png" -w 64 -h 64 "Y.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/z_cm.png" -w 64 -h 64 "zcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Z_cm.png" -w 64 -h 64 "Zcm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/z_cs.png" -w 64 -h 64 "zcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Z_cs.png" -w 64 -h 64 "Zcs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/zeta_cm.png" -w 64 -h 64 "zetacm.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/zeta_cs.png" -w 64 -h 64 "zetacs.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/zeta_jvn.png" -w 64 -h 64 "zetajvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/zeta_phv.png" -w 64 -h 64 "zetaphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/zeta.png" -w 64 -h 64 "zeta.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/z_jvn.png" -w 64 -h 64 "zjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Z_jvn.png" -w 64 -h 64 "Zjvn.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/z_phv.png" -w 64 -h 64 "zphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Z_phv.png" -w 64 -h 64 "Zphv.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/z.png" -w 64 -h 64 "z.svg" -y 1.0 -b #ffffff
inkscape -z -e "pngs/Z.png" -w 64 -h 64 "Z.svg" -y 1.0 -b #ffffff
